### PR TITLE
New features final additions

### PR DESCRIPTION
**Pull request by ZSandor-dev**
Please review slight changes added in the client code (create and populate dictionary) and renaming of two functions in the unit test files with encryption.

### CODE REVIEW

**Comment by ShorouqTelfah** [comment]
comment the final modifications

**Review by ShorouqTelfah — COMMENTED** [review]
approve changes.

**Review by Niccolleezk — APPROVED** [review]
changed noted. ? issue with Client.py

**Comment by ZSandor-dev** [comment]
This pull request is closed and replaced with another one.

**Pull request closed without merging**
